### PR TITLE
fixing SDXL Sampler V3 to work with newest version of ComfyUI

### PR DESCRIPTION
**Pull request by jobunk**
As discussed here https://github.com/SeargeDP/SeargeSDXL/issues/137 some of the sampler functions of ComfyUI were moved around, causing SeargeSDXL to no longer load.

After fixing that issue there still were problems with the SDXL Sampler, which led to errors when running that specific module. I managed to get rid of these errors and it seems to work fine for me now. However I'm not very familiar with this project's / ComfyUI's code and have a distaste for python, so please make sure to double check everything I did. 

I also only added backwards compatibility for the loading issue. If you also want it for executing the sampler feel free to add it.

EDIT: The changes from this PR have been added to the main repo. Thanks a lot @SeargeDP

### CODE REVIEW

**Comment by escalate007** [comment]
thanks，it's ok now~

**Comment by Elminsst** [comment]
i have fixed the files，but it still don‘t worked:

Error occurred when executing SeargeSDXLSamplerV3:
'SDXL' object has no attribute 'get_model_object'
File "D:\AI\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\AI\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\AI\ComfyUI\ComfyUI\custom_nodes\deforum-comfy-nodes\deforum_nodes\exec_hijack.py", line 55, in map_node_over_list
return orig_exec(obj, input_data_all, func, allow_interrupt)
File "D:\AI\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\AI\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL\modules\_legacy.py", line 167, in sample
return sdxl_ksampler(base_model, refiner_model, noise_seed, base_steps, refiner_steps, cfg, sampler_name,
File "D:\AI\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL\modules\custom_sdxl_ksampler.py", line 366, in sdxl_ksampler
samples = sdxl_sample(base_model, refiner_model, noise, base_steps, refiner_steps, cfg, sampler_name, scheduler,
File "D:\AI\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL\modules\custom_sdxl_ksampler.py", line 193, in sdxl_sample
base_sampler = comfy.samplers.KSampler(real_base_model, steps=steps, device=device, sampler=sampler_name,
File "D:\AI\ComfyUI\ComfyUI\comfy\samplers.py", line 705, in __init__
self.set_steps(steps, denoise)
File "D:\AI\ComfyUI\ComfyUI\comfy\samplers.py", line 726, in set_steps
self.sigmas = self.calculate_sigmas(steps).to(self.device)
File "D:\AI\ComfyUI\ComfyUI\comfy\samplers.py", line 717, in calculate_sigmas
sigmas = calculate_sigmas(self.model.get_model_object("model_sampling"), self.scheduler, steps)
File "D:\AI\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1688, in __getattr__
raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

**Comment by JimB99** [comment]
It fixed the general text2img for me, but inpainting seems to completely ignore the prompt and instead do img2img for the mask. Anybody else have the same problem?

**Comment by jobunk** [comment]
@JimB99 Ah damn it. In my current workflow I only use text2img, which as you said seems to work fine. I will have to sit down and look into the img2img at some point. As I said I'm not familiar with this code, so it is very possible that I missed or broke something. Sadly I'm pretty busy right now... The maintainer of this project could probably fix it a lot faster.

@Elminsst This error looks a lot like the one I fixed... The line "D:\AI\ComfyUI\ComfyUI\custom_nodes\deforum-comfy-nodes\deforum_nodes\exec_hijack.py" I don't remember seeing though.

**Comment by JimB99** [comment]
@jobunk Don't worry about it, it seems to not be your fix that broke it, but rather the comfyui update I think. Or something entirely different on my end. I will let you know if I figure it out :)

**Comment by lovisdotio** [comment]
After updating with yout filed , I got this error after from Ksampler :
Error occurred when executing KSampler (Efficient):

module 'comfy.sample' has no attribute 'prepare_mask'

**Comment by Anyeos** [comment]
I don't understand but is it included in the "main" branch? Because I have everything fromt github but the error stills exists.

**Comment by jobunk** [comment]
> I don't understand but is it included in the "main" branch? Because I have everything fromt github but the error stills exists.

Yes it should be included in the main branch now. See the commits:
https://github.com/SeargeDP/SeargeSDXL/commit/1df4b184db1c2b35a6d229b811d08479abb0d6d8
https://github.com/SeargeDP/SeargeSDXL/commit/2eb5edbc712329d77d1a2f5f1e6c5e64397a4a83

Either you are not actually on the latest version, or there were more changes to comfy UI itself. Sadly I don't have time to investigate anytime soon.

**Pull request closed without merging**
